### PR TITLE
Create apple-m2.org

### PR DESCRIPTION
**Pull request by jdtsmith**

### CODE REVIEW

**Comment by enzuru** [comment]
Thanks @jdtsmith !

**Comment by jdtsmith** [comment]
Sure thing.  BTW, I noticed your use of some dev gcc versions really sped up your AMD result.  Any thoughts as to how/why?

**Comment by enzuru** [comment]
@jdtsmith no idea what @cpbotha was up to

**Comment by enzuru** [comment]
@jdtsmith  would you be interested in re-running the benchmark with the following more accurate Emacs settings?

```lisp
(setq elb-speed native-comp-speed)
(setq elb-safety compilation-safety)
```

**Pull request merged**
