### PR TITLE
Adds Emacs v28 and v29 benchmark run on an intel-core-i7-4960HQ.

### PR DESCRIPTION
**Pull request by grettke**
Adds Emacs v28 and v29 benchmark run on an intel-core-i7-4960HQ.

### CODE REVIEW

**Comment by enzuru** [comment]
@grettke is this native comp? Slower than I would have expected.

**Comment by grettke** [comment]
> @grettke is this native comp? Slower than I would have expected.

This is https://emacsformacos.com/ which I love. Based on what I can find it doesn't appear to be native compiled.

**Comment by grettke** [comment]
Just tried what looks like a native build since it spend 5 minutes compiling and the docs explain it is native and the benchmark took 139.50 instead. Interesting.

**Comment by enzuru** [comment]
This repo is only for native compilation, so you'd need to update the PR with the latest results.

**Comment by grettke** [comment]
Understood. When I do, I will reopen this request.

**Pull request closed without merging**
