### PR TITLE
Add Intel Core i7-1355U

### PR DESCRIPTION
**Pull request by charmitro**

### CODE REVIEW

**Comment by enzuru** [comment]
Thank you!

**Comment by enzuru** [comment]
@charmitro  would you be interested in re-running the benchmark with the following more accurate Emacs settings?

```lisp
(setq elb-speed native-comp-speed)
(setq elb-safety compilation-safety)
```

**Comment by charmitro** [comment]
> @charmitro would you be interested in re-running the benchmark with the following more accurate Emacs settings?
> 
> ```commonlisp
> (setq elb-speed native-comp-speed)
> (setq elb-safety compilation-safety)
> ```

@enzuru unfortunately I no longer use the same CPU. I can however provide for AMD Ryzen 7 9800X3D 8-Core.

**Comment by enzuru** [comment]
@charmitro that works

**Pull request merged**
